steps:

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull europe-west1-docker.pkg.dev/playground-s-11-97bbb142/my-repo1/my-proj1:latest || exit 0']


- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/playground-s-11-97bbb142/my-repo1/my-proj1', 
       '--cache-from',  'europe-west1-docker.pkg.dev/playground-s-11-97bbb142/my-repo1/my-proj1' , '.' ]


images:
- 'europe-west1-docker.pkg.dev/playground-s-11-97bbb142/my-repo1/my-proj1'  
